name: 'Arch Linux Package Builder'
description: 'Builds packages and produces a repository'
inputs:
  PRIVATE_KEY:
    required: true
    description: something
  PUBLIC_KEY:
    required: true
    description: something
  PACKAGER:
    required: true
    description: something
  GPGKEY:
    required: true
    description: something
  REPONAME:
    required: true
    description: something
runs:
  using: 'docker'
  image: 'docker://ingram/archlinux-abs:latest'
  env:
    PRIVATE_KEY: ${{ inputs.PRIVATE_KEY }}
    PUBLIC_KEY: ${{ inputs.PUBLIC_KEY }}
    PACKAGER: ${{ inputs.PACKAGER }}
    GPGKEY: ${{ inputs.GPGKEY }}
    REPONAME: ${{ inputs.REPONAME }}
  args:
    - su -l makepkg -c "echo $PRIVATE_KEY | gpg --import"
    - su -l makepkg -c "echo $PUBLIC_KEY | gpg --import"
    - pacman -Syu --nonconfirm
    - mkdir /build
    - cp -r * /build
    - chown -R builder /build
    - su -l makepkg -c 'cd /build && PACKAGER=$PACKAGER GPGKEY=$GPGKEY makepkg --sign --noconfirm -s'
    - mkdir /repo
    - mv /build/*.pkg.tar.xz /build/*.pkg.tar.xz.sign /repo
    - cd /repo
    - repo-add $REPONAME.db *.pkg.tar.xz
    - mv /repo $GITHUB_WORKSPACE
