name: 'Arch Linux Package Builder'
description: 'Builds packages and produces a repository'
inputs:
  PRIVATE_KEY:
    required: true
    description: something
  PUBLIC_KEY:
    required: true
    description: something
  PACKAGER:
    required: true
    description: something
  GPGKEY:
    required: true
    description: something
  REPONAME:
    required: true
    description: something
runs:
  using: 'docker'
  image: 'docker://ingram/archlinux-abs:latest'
  env:
    PRIVATE_KEY: ${{ inputs.PRIVATE_KEY }}
    PUBLIC_KEY: ${{ inputs.PUBLIC_KEY }}
    PACKAGER: ${{ inputs.PACKAGER }}
    GPGKEY: ${{ inputs.GPGKEY }}
    REPONAME: ${{ inputs.REPONAME }}

